### PR TITLE
Added support for MacOS to project configuration

### PR DESCRIPTION
**Pull request by jake-pauls**
**Overview**
Updated `*.premake5.lua` configuration files to include support for MacOS using the `gmake2` toolset.
Also ported the various build/clean/test `.bat` files to a CLI tool written in Python that has some additional quality of life features which were not previously included in the Batchfiles.

### CODE REVIEW

**Review by kiwon132445 — APPROVED** [review]

**Comment by jake-pauls** [comment]
Since this effects @junekaa06's workflow the most, please hold off on merging this PR until he approves - despite the two reviewer rule. 🪨

**Comment by jake-pauls** [comment]
[Port Project Configuration to MacOS](https://trello.com/c/rcKe7BNW/4-port-project-configuration-to-macos)

**Comment by mbajaman** [comment]
@junekaa06 Did you have a chance to test this out so we can merge it to dev?

**Review by junekaa06 — APPROVED** [review]
LGTM

**Review by paulc100 — APPROVED** [review]

**Review by paulc100 — APPROVED** [review]
LGTM

**Review by mbajaman — COMMENTED** [review]
Went through the code just so i have a sense of where things are :)
Thanks 🚀

**Pull request merged**
